- desc: 9613fafd
  port: 4727
  bp: 4728
  ip: 127.0.0.1
  desired_caps:
    deviceName: xxxxxxx
    udid: 9613fafd
    platformVersion: 7.1.2
    platformName: Android
    automationName: uiautomator2
    systemPort: 8201
    appPackage: com.yozo.office
    autoGrantPermissions: !!bool True
    noReset:  !!bool True
    appActivity: com.yozo.office.MainAppActivity
    newCommandTimeout: 120