desc: vivoX9 Plus
port: 4723
bp: 4724
ip: 127.0.0.1
desired_caps:
  deviceName: vivoX9 Plus
  udid: 9613fafd
  platformVersion: 7.1.2
  platformName: Android
  automationName: uiautomator2
  systemPort: 8200
  appPackage: com.yozo.office
#  appPackage: com.ebensz.office.entry
  noReset:  !!bool True
  appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
  newCommandTimeout: 120

