- desc: 9613fafd
  port: 4727
  bp: 4728
  ip: 127.0.0.1
  desired_caps:
    deviceName: xxxxxxx
    udid: 9613fafd
    platformVersion: 7.1.2
    platformName: Android
    automationName: uiautomator2
    systemPort: 8201
    appPackage: com.yozo.office
    #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120

- desc: 127.0.0.1:62001
  port: 4725
  bp: 4726
  ip: 127.0.0.1
  desired_caps:
    deviceName: yeshen01
    udid: 127.0.0.1:62001
    platformVersion: 5.1.1
    platformName: Android
    automationName: uiautomator2
    systemPort: 8201
    appPackage: com.yozo.office
  #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120

- desc: 127.0.0.1:62025
  port: 4727
  bp: 4728
  ip: 127.0.0.1
  desired_caps:
    #模拟器
    deviceName: yeshen02
    udid: 127.0.0.1:62025
    platformVersion: 5.1.1
    platformName: Android
    automationName: uiautomator2
    systemPort: 8202
    appPackage: com.yozo.office
    #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120

- desc: 127.0.0.1:62026
  port: 4729
  bp: 4730
  ip: 127.0.0.1
  desired_caps:
    #模拟器
    deviceName: yeshen03
    udid: 127.0.0.1:62026
    platformVersion: 5.1.1
    platformName: Android
    automationName: uiautomator2
    systemPort: 8203
    appPackage: com.yozo.office
    #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120

- desc: 127.0.0.1:62027
  port: 4731
  bp: 47332
  ip: 127.0.0.1
  desired_caps:
    #模拟器
    deviceName: yeshen04
    udid: 127.0.0.1:62027
    platformVersion: 5.1.1
    platformName: Android
    automationName: uiautomator2
    systemPort: 8204
    appPackage: com.yozo.office
    #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120

- desc: 127.0.0.1:62028
  port: 4733
  bp: 4734
  ip: 127.0.0.1
  desired_caps:
    #模拟器
    deviceName: yeshen05
    udid: 127.0.0.1:62028
    platformVersion: 5.1.1
    platformName: Android
    automationName: uiautomator2
    systemPort: 8205
    appPackage: com.yozo.office
    #  appPackage: com.ebensz.office.entry
    noReset:  !!bool True
    appActivity: com.yozo.home.WelcomeActivity #真机需要从最开始的activity进入
    newCommandTimeout: 120